### ISSUE TITLE
SHIPLIST (1.0.0)

### ISSUE THREAD

**Issue by Tjoosten** [IonAuth/IonAuth#13]
The shiplist of the first version
=======================

- [ ] #1 Abstract email functionality. -> **David is working on that.**
- [ ] #2 Use PDO of Illuminate DB.
- [ ] #3 Separate logic into classes.`
- [x] #4 Switch to using a config object. -> **Closed by Kayla.**
- [ ] #5 Pass in language object for internationalization
- [x] #6 Use Apigen for docs. -> **[The docs](http://ionauth.github.io/Docs)**
- [x] #9 Add license.
- [x] #10 Add contributing file.
- [x] #11 Set labels in the issue tracker
- [ ] #12 Lang support files. -> **Tim added the lang files**
- [ ] #14 CamelCase missing on 2 functions
- [x] #15 Gitter support -> **Not for now**
- [ ] #18 Create separate repo for example app
- [ ] #20 Database migrations
- [ ] #21 Group object
- [ ] #22 User object
